/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"
#include <android/log.h>
#include <android/bitmap.h>
#include <android/native_window_jni.h>
#include <opencv2/features2d/features2d.hpp>

#include <algorithm>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <math.h>
/* Header for class com_netvirta_netvisioncamera2_JNIUtils */


using namespace std;
using namespace cv;

#ifndef int64_t
#define int64_t long long
#endif

#ifndef uint8_t
#define uint8_t unsigned char
#endif

#ifndef int32_t
#define int32_t int
#endif

#ifndef uint32_t
#define uint32_t unsigned int
#endif

#ifndef _Included_com_netvirta_netvisioncamera2_JNIUtils
#define _Included_com_netvirta_netvisioncamera2_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_netvirta_netvisioncamera2_JNIUtils
 * Method:    detectLine
 * Signature: (IILjava/nio/ByteBuffer;Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_netvirta_netvisioncamera2_JNIUtils_detectLine
  (JNIEnv *, jclass, jint, jint, jobject, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
